### PR TITLE
Add expunge_all and lock for all db transactions

### PR DESCRIPTION
**Pull request by z00sts**

### CODE REVIEW

**Comment by z00sts** [comment]
!test

**Comment by z00sts** [comment]
!test

**Comment by z00sts** [comment]
!test

**Comment by z00sts** [comment]
!test

**Comment by z00sts** [comment]
!test

**Comment by z00sts** [comment]
!test

**Review by sh0ked — APPROVED** [review]

**Comment by z00sts** [comment]
!test

**Comment by z00sts** [comment]
!test

**Pull request merged**
