### PR TITLE
Fix vmmaster_cleanup performance issue

### PR DESCRIPTION
**Pull request by z00sts**
Add indexes for foreign keys in vmmaster_log_steps and session_log_steps.
Add backrefs in models.
Refactor cleanup algorithm: removing whole directories, cascade deleting.

### CODE REVIEW

**Comment by z00sts** [comment]
!test

**Comment by z00sts** [comment]
!test

**Comment by z00sts** [comment]
!test

**Comment by z00sts** [comment]
!test

**Comment by nwlunatic** [comment]
:+1:

**Comment by sh0ked** [comment]
ну фиг знает =)) :+1:

**Pull request merged**
