### PR TITLE
Split vmmaster and provider

### PR DESCRIPTION
**Pull request by sh0ked**
- 2 Applications Types: Provider and Head
- Setting PUBLIC_IP for Provider Application (uses in process of creation endpoints)
- Every application have API
- Communication in database

### CODE REVIEW

**Comment by z00sts** [comment]
!test

**Comment by sh0ked** [comment]
!test

**Comment by sh0ked** [comment]
⚠️   Функциональные тесты само собой не пройдут пока не будет переделан деплой.

**Review by z00sts — APPROVED** [review]

**Comment by sh0ked** [comment]
!test

**Comment by sh0ked** [comment]
!test

**Comment by sh0ked** [comment]
!test

**Pull request merged**
