### PR TITLE
Run websocket script in separate thread

### PR DESCRIPTION
**Pull request by z00sts**

### CODE REVIEW

**Comment by z00sts** [comment]
!test

**Comment by z00sts** [comment]
!test

**Comment by z00sts** [comment]
!test

**Comment by z00sts** [comment]
!test

**Comment by sh0ked** [comment]
:+1:

**Comment by sh0ked** [comment]
@z00sts может тест добавить?

**Comment by z00sts** [comment]
@sh0ked добавлю

**Comment by z00sts** [comment]
!test

**Comment by z00sts** [comment]
!test

**Comment by z00sts** [comment]
!test

**Pull request merged**
