### PR TITLE
Deleted field for session model

### PR DESCRIPTION
**Pull request by z00sts**
datetime field

### CODE REVIEW

**Comment by z00sts** [comment]
!test

**Comment by z00sts** [comment]
!test

**Comment by z00sts** [comment]
!test

**Comment by z00sts** [comment]
!test

**Comment by z00sts** [comment]
!test

**Comment by z00sts** [comment]
!test

**Comment by z00sts** [comment]
!test

**Comment by z00sts** [comment]
review @nwlunatic @sh0ked

**Comment by z00sts** [comment]
!test

**Comment by sh0ked** [comment]
:+1:

**Pull request merged**
