### PR TITLE
add log_size in integrational tests config

### PR DESCRIPTION
**Pull request by sh0ked**

### CODE REVIEW

**Comment by sh0ked** [comment]
!test

**Comment by sh0ked** [comment]
!test

**Comment by sh0ked** [comment]
!test

**Comment by sh0ked** [comment]
!test

**Comment by sh0ked** [comment]
!test

**Comment by sh0ked** [comment]
!test

**Comment by sh0ked** [comment]
!test

**Comment by z00sts** [comment]
:+1:

**Pull request merged**
